Fix cannot find arc-elf cross tool
kbuild/kbuild.sh: change arc cross tool name to arc-linux. This name is valid for all gcc versions

Error: Cannot find arc-elf under https://cdn.kernel.org/pub/tools/crosstool/files/bin/x86_64/

kbuild/make.cross: change cross tool matching pattern. Avoid sparc-linux being used instead of arc-linux

Error: lftpget -c https://cdn.kernel.org/pub/tools/crosstool/files/bin/x86_64/./14.2.0/x86_64-gcc-14.2.0-nolibc-sparc-linux.tar.xz

Signed-off-by: Costin Constantin <costin.constantin@nxp.com>